# Generated by Django 5.1.4 on 2024-12-17 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('NEW_ITEM', 'New Item'), ('INCREASE', 'Increase'), ('DECREASE', 'Decrease')], max_length=10)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('previous_quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_transaction_logs', to='core.company')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_logs', to='core.inventoryitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_transaction_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['company'], name='core_invent_company_3e835b_idx'), models.Index(fields=['user'], name='core_invent_user_id_c61f1b_idx'), models.Index(fields=['inventory_item'], name='core_invent_invento_09aac6_idx'), models.Index(fields=['transaction_type'], name='core_invent_transac_429583_idx')],
            },
        ),
    ]
