# Generated by Django 5.1.4 on 2024-12-26 09:15

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_inventorytransactionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.FileField(blank=True, upload_to=core.models.upload_to),
        ),
    ]
